language: python
os: linux
dist: xenial

python:
  - "3.7"

before_script:
  - pip install --upgrade pip
  - pip install wheel

install:
  - pip install -r requirements.txt
  - pip install --upgrade venvipy

script:
  - ls -la /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms
  - locate libxkbcommon-x11.so.0
