language: python
os: linux
dist: trusty
sudo: required

python:
  - "3.7"
  - "3.8"

virtualenv:
  system_site_packages: true

before_script:
  - sudo apt-get update
  - sudo apt-get -y install python3-pyqt5
  - pip install --upgrade pip
  - pip install wheel

install:
  - pip install -r requirements.txt
  - pip install --upgrade venvipy

script:
  - venvipy
