language: python
os: linux
dist: xenial

python:
  - "3.7"

before_script:
  - export QT_DEBUG_PLUGINS=1
  - pip install --upgrade pip
  - pip install wheel

install:
  - pip install -r requirements.txt
  - pip install --upgrade venvipy

script:
  - venvipy
