language: python
os: linux
dist: xenial

services:
  - xvfb

python:
  - "3.7"

before_script:
  - sudo apt-get install libxkbcommon-x11-0
  - "export DISPLAY=:99.0"

install:
  - pip install venvipy==0.2.4

script:
  - xvfb-run -a tests/test.sh
