language: python
os: linux
dist: xenial

python:
  - "3.7"

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pylint

before_script:
  - pip install git+https://github.com/sinusphi/venvipy.git
  - cd /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/venvipy

script:
  - pylint --exit-zero --output-format=colorized --reports=y --verbose --disable=no-name-in-module --disable=invalid-name --disable=missing-function-docstring --ignore=venvipy_rc.py *