language: python
os: linux
dist: xenial

python:
  - "3.7"

install:
  - pip install venvipy==0.2.4

script:
  - python /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/venvipy/venvi.py
