language: python
os: linux
dist: xenial

python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install wheel

script:
  - pip install git+https://github.com/sinusphi/venvipy.git
